handleL=figure(1);
set (handleL,'Units','normalized','Position',[0.3 0.3 0.4 0.4]);
handleB_login = uicontrol('Parent',handleL,...          %打开主界面
    'Units','normalized','Position',[0.7 0.2 0.20 0.12],...
    'Style','pushbutton','String','学生登录',...
    'FontSize',14,'FontName', 'SimHei','BackgroundColor',[1 1 0],...
    'Callback','GUI_login_ref;');
handleE_S = uicontrol('Parent',handleL,...        %学号的动态文本
    'Units','normalized','Position',[0.2 0.6 0.3 0.2],...
    'Style','edit','String','请输入学号',...
    'FontSize',16,'FontName', 'SimHei');
handleE_N = uicontrol('Parent',handleL,...        %姓名的动态文本
    'Units','normalized','Position',[0.2 0.2 0.3 0.2],...
    'Style','edit','String','请输入姓名',...
    'FontSize',16,'FontName', 'SimHei');