%实验参数初始化
step_size = 0.002;      %仿真文件控制周期，设定为0.002，不可改动
simulink_time = 5.0;    %仿真文件仿真时间，设定为5.0，不可改动
Plant_K = 140;          %被控对象增益，初始为140，输入学号可改动
Plant_T1 = 0.08;        %被控对象机电时间常数，初始为0.08，输入学号可改动
Plant_T2 = 0.006;       %被控对象电磁时间常数，初始为0.006，不可改动
Kp1 =0.1;               %PID控制器的P项，初始值为0.1，输入参数可改动
Ki1 =0.001;             %PID控制器的I项，初始值为0.001，输入参数可改动
Kd1 = 0.001;            %PID控制器的D项，初始值为0.001，输入参数可改动
Student_num = 0;        %学生学号，初始值为0，输入学号可改动
Student_name = {'Name'};   %学生姓名，初始值为‘Name’，输入姓名可改动
exp_model = 0;          %实验模式，初始值为0；为0对应实验A，为1对应实验B，选择模式可改动
simulink_start_time = 1.0;  %仿真输入信号（阶跃信号）开始时间，初始值为1.0，目前不可改动，后续可设计为可以改动项
motor_run_flag = 0;     %电机运行记录标志位
r = zeros(2501,1);      %实验的输入信号
y = zeros(2501,1);      %实验的输出信号
u = zeros(2501,1);
%打开实验主界面
handleF=figure;
set (handleF,'Units','normalized','Position',[0.1 0.15 0.8 0.7]);
handleA_scope = axes;
set (handleA_scope,'Units','normalized','Position',[0.1 0.5 0.8 0.4]);
xlabel('时间/s');
ylabel('位置/°');

handleB_login = uicontrol('Parent',handleF,...          %打开学生登录界面
    'Units','normalized','Position',[0.05 0.25 0.12 0.12],...
    'Style','pushbutton','String','学生登录',...
    'FontSize',[12],'FontName', 'SimHei',...
    'Callback','GUI_login_ref;set(handleB_login,''BackgroundColor'',[1 0 0]);');
handleB_model = uicontrol('Parent',handleF,...          %打开实验模式选取面板
    'Units','normalized','Position',[0.05 0.05 0.12 0.12],...
    'Style','pushbutton','String','实验模式',...
    'FontSize',[12],'FontName', 'SimHei',...
    'Callback','GUI_model_ref;set(handleB_model,''BackgroundColor'',[1 0 0]);');
handleB_control = uicontrol('Parent',handleF,...        %打开控制器参数设置面板
    'Units','normalized','Position',[0.25 0.25 0.12 0.12],...
    'Style','pushbutton','String','控制器参数设置',...
    'FontSize',[12],'FontName', 'SimHei',...
    'Callback','GUI_PID_ref');
handleB_run = uicontrol('Parent',handleF,...            %运行仿真程序
    'Units','normalized','Position',[0.25 0.05 0.12 0.12],...
    'Style','pushbutton','String','运行电机',...
    'FontSize',[12],'FontName', 'SimHei',...
    'Callback','motor_run_flag = 1;load(''ref1.mat'');load(''model_ref.mat'');load(''Student_ref.mat'');sim(''Experiment2_PID_model'');pause(2.0);warndlg(''电机运行成功'')');

handleB_plot = uicontrol('Parent',handleF,...           %绘制仿真数据
    'Units','normalized','Position',[0.45 0.25 0.12 0.12],...
    'Style','pushbutton','String','绘制输出曲线','BackgroundColor',[1 1 0],...
    'FontSize',[12],'FontName', 'SimHei',...
    'Callback','delete(allchild(handleA_scope));GUI_scope;');
handleB_plot_e = uicontrol('Parent',handleF,...           %绘制误差数据
    'Units','normalized','Position',[0.65 0.25 0.12 0.12],...
    'Style','pushbutton','String','绘制误差曲线','BackgroundColor',[1 1 0],...
    'FontSize',[12],'FontName', 'SimHei',...
    'Callback','delete(allchild(handleA_scope));GUI_plot_e;');
handleB_plot_u = uicontrol('Parent',handleF,...           %绘制控制量数据
    'Units','normalized','Position',[0.65 0.05 0.12 0.12],...
    'Style','pushbutton','String','绘制控制量曲线','BackgroundColor',[1 1 0],...
    'FontSize',[12],'FontName', 'SimHei',...
    'Callback','delete(allchild(handleA_scope));GUI_plot_u;');

handleB_mark = uicontrol('Parent',handleF,...           %一键评分
    'Units','normalized','Position',[0.85 0.25 0.12 0.12],...
    'Style','pushbutton','String','一键评分','BackgroundColor',[0 1 0],...
    'FontSize',[12],'FontName', 'SimHei',...
    'Callback','step_mark;');
handleB_save = uicontrol('Parent',handleF,...           %保存实验数据
    'Units','normalized','Position',[0.85 0.05 0.12 0.12],...
    'Style','pushbutton','String','保存数据','BackgroundColor',[0 1 0],...
    'FontSize',[12],'FontName', 'SimHei',...
    'Callback','delete(allchild(handleA_scope));GUI_save_data;');







% GUI_PID_ref;
% load ('ref1.mat')
% sim ('Experiment2_PID_model');
